# Training settings Proposed
exps_dir: 'experiments'
iter_log_interval: 1
iter_time_window: 100
model_save_interval: 1
seed: 1
backup:
model:
  name: HorizonRegression
  parameters:
    num_outputs: 5 # 1conf+1pred_left_endpoint+1pred_right_endpoint+pred_k+pred_b
    pretrained: false #true
    backbone: 'resnet18'
    pred_category: false
    curriculum_steps: [0, 0, 0, 0]
loss_parameters:
  conf_weight: 100
  left_point_weight: 100
  right_point_weight: 100
  poly_weight: 100
batch_size: 20
epochs: 500
optimizer:
  name: Adam
  parameters:
    lr: 2.0e-3
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 400

# Testing settings
test_parameters:
  conf_threshold: 0.5  #0.5

# Dataset settings
datasets:
  train:
    type: HorizonDataset
    parameters:
      dataset: HorizonSet
      split: train
      img_size: [288, 384] # [height, width]
      normalize: true #False #true
      root: "./data/train_set"

  test: &test
    type: HorizonDataset
    parameters:
      dataset: HorizonSet
      split: test
      Horizon_num: 1
      img_size: [288, 384]
      root: "./data/test_set"
      normalize: true #true
      augmentations: []

  test5:
    type: HorizonDataset
    parameters:
      dataset: HorizonSet
      split: test5
      Horizon_num: 1
      img_size: [288, 384]
      root: "./data/test_set"
      normalize: true #true
      augmentations: []


  val:
    type: HorizonDataset
    parameters:
      dataset: HorizonSet
      split: val
      Horizon_num: 1
      img_size: [288, 384]
      root: "./data/val_set"
      normalize: true #true
      augmentations: []

